import type { ChapterSummaryEntry, StudyCard } from "./course-data";

const support = (...ids: string[]) => ids;

export const chapter4StudyCards: StudyCard[] = [
  {
    id: "c4-f1",
    chapterId: 4,
    title: "Битва на реке Калке",
    sortKey: 100,
    time: "1223 г.",
    place: "река Калка",
    participants: ["русские князья", "монголы"],
    essence: "Битва на реке Калке произошла в 1223 году.",
    results: "Это первое крупное столкновение русских князей с монголами.",
    supportsPracticeItemIds: support("c4-ft-v1-q23"),
  },
  {
    id: "c4-f2",
    chapterId: 4,
    title: "Невская битва",
    sortKey: 110,
    time: "1240 г.",
    place: "река Нева",
    participants: ["Александр Невский", "шведы"],
    essence: "Невская битва произошла в 1240 году.",
    results: "Победа укрепила безопасность Новгорода на северо-западном направлении.",
    supportsPracticeItemIds: support("c4-ft-v1-q23"),
  },
  {
    id: "c4-f3",
    chapterId: 4,
    title: "Куликовская битва",
    sortKey: 120,
    time: "1380 г.",
    place: "Куликово поле",
    participants: ["Дмитрий Донской", "Мамай"],
    essence: "Куликовская битва произошла в 1380 году.",
    results: "Победа повысила авторитет Москвы как центра сопротивления Орде.",
    supportsPracticeItemIds: support("c4-ft-v1-q23"),
  },
  {
    id: "c4-f4",
    chapterId: 4,
    title: "Стояние на реке Угре",
    sortKey: 130,
    time: "1480 г.",
    place: "река Угра",
    participants: ["Иван III", "хан Ахмат"],
    essence: "Стояние на реке Угре произошло в 1480 году.",
    results: "Оно завершило зависимость Руси от Орды.",
    supportsPracticeItemIds: support("c4-ft-v1-q23"),
  },
  {
    id: "c4-f5",
    chapterId: 4,
    title: "Автокефалия Русской церкви",
    sortKey: 140,
    time: "1448 г.",
    place: "Москва",
    participants: ["русское духовенство", "митрополит Иона"],
    essence: "В 1448 году было принято решение об автокефалии Русской православной церкви.",
    results: "Русская церковь стала независимой в управлении.",
    supportsPracticeItemIds: support("c4-ft-v2-q17"),
  },
  {
    id: "c4-f6",
    chapterId: 4,
    title: "Крымское ханство выделяется из Орды",
    sortKey: 150,
    time: "XV в.",
    place: "Крым",
    participants: ["крымские ханы", "ордынцы"],
    essence: "В XV веке из Золотой Орды выделилось Крымское ханство.",
    results: "Распад Орды создал новые политические силы у южных рубежей Руси.",
    supportsPracticeItemIds: support("c4-ft-v3-q17"),
  },
  {
    id: "c4-f7",
    chapterId: 4,
    title: "Ярославское княжество присоединено к Москве",
    sortKey: 160,
    time: "1463 г.",
    place: "Ярославль",
    participants: ["Иван III", "московская власть"],
    essence: "Ярославское княжество было присоединено к Москве в 1463 году.",
    results: "Это было одним из ранних шагов московского собирания земель.",
    supportsPracticeItemIds: support("c4-ft-v3-q24"),
  },
  {
    id: "c4-f8",
    chapterId: 4,
    title: "Новгородская земля присоединена к Москве",
    sortKey: 170,
    time: "1478 г.",
    place: "Великий Новгород",
    participants: ["Иван III", "новгородцы"],
    essence: "Новгородская земля была присоединена к Москве в 1478 году.",
    results: "Иван III ликвидировал новгородскую самостоятельность.",
    supportsPracticeItemIds: support("c4-ft-v3-q24"),
  },
  {
    id: "c4-f9",
    chapterId: 4,
    title: "Тверь присоединена к Москве",
    sortKey: 180,
    time: "1485 г.",
    place: "Тверь",
    participants: ["Иван III", "тверской князь Михаил Борисович"],
    essence: "Тверь была присоединена к Москве в 1485 году.",
    results: "После этого Москва закрепила преимущество в Северо-Восточной Руси.",
    supportsPracticeItemIds: support("c4-ft-v3-q24"),
  },
  {
    id: "c4-f10",
    chapterId: 4,
    title: "Смоленск присоединён при Василии III",
    sortKey: 190,
    time: "1514 г.",
    place: "Смоленск",
    participants: ["Василий III", "русские войска"],
    essence: "Смоленск был присоединён к Русскому государству в 1514 году при Василии III, а не при Иване III.",
    results: "Этот факт отличает Смоленск от Новгорода, Твери и Ярославля.",
    supportsPracticeItemIds: support("c4-ft-v3-q12", "c4-ft-v3-q24"),
  },
  {
    id: "c4-f11",
    chapterId: 4,
    title: "Судебник Ивана III",
    sortKey: 200,
    time: "1497 г.",
    place: "Москва",
    participants: ["Иван III", "судьи", "служилые люди"],
    essence: "Судебник Ивана III 1497 года был первым общерусским сводом законов.",
    results: "Он укрепил единые правовые нормы Русского государства.",
    supportsPracticeItemIds: support("c4-ft-v3-q15"),
  },
  {
    id: "c4-f12",
    chapterId: 4,
    title: "Юрьев день по Судебнику",
    sortKey: 201,
    time: "1497 г.",
    place: "Русское государство",
    participants: ["крестьяне", "землевладельцы"],
    essence: "По Судебнику 1497 года крестьянам разрешалось переходить от одного владельца к другому в Юрьев день.",
    results: "Юрьев день стал законным сроком крестьянского перехода.",
    supportsPracticeItemIds: support("c4-ft-v3-q16"),
  },
  {
    id: "c4-f13",
    chapterId: 4,
    title: "Пожилое при переходе крестьянина",
    sortKey: 202,
    time: "1497 г.",
    place: "Русское государство",
    participants: ["крестьяне", "землевладельцы"],
    essence: "Пожилым называли платёж крестьянина владельцу земли при переходе в Юрьев день.",
    results: "Пожилое было связано с ограничением крестьянского перехода.",
    supportsPracticeItemIds: support("c4-ft-v4-q19"),
  },
  {
    id: "c4-f14",
    chapterId: 4,
    title: "Кормление должностных лиц",
    sortKey: 210,
    time: "XV—XVI вв.",
    place: "Русское государство",
    participants: ["должностные лица", "местное население"],
    essence: "Кормлением называли систему содержания должностных лиц за счёт местного населения.",
    results: "Кормление было одной из черт управления Русского государства.",
    supportsPracticeItemIds: support("c4-ft-v2-q18"),
  },
  {
    id: "c4-f15",
    chapterId: 4,
    title: "Местничество",
    sortKey: 211,
    time: "конец XV — XVI в.",
    place: "Русское государство",
    participants: ["бояре", "служилые князья"],
    essence: "Местничество распределяло должности в зависимости от знатности происхождения и службы предков.",
    results: "Эта система порождала споры о старшинстве родов.",
    supportsPracticeItemIds: support("c4-ft-v3-q18"),
  },
  {
    id: "c4-f16",
    chapterId: 4,
    title: "Дети боярские",
    sortKey: 212,
    time: "XV в.",
    place: "Русское государство",
    participants: ["дети боярские"],
    essence: "Детьми боярскими называли категорию служилых людей, потомков провинциальных бояр, которые несли военную службу за поместья.",
    results: "Они были важной частью служилого слоя Московского государства.",
    supportsPracticeItemIds: support("c4-ft-v3-q19"),
  },
  {
    id: "c4-f17",
    chapterId: 4,
    title: "Собирание русских земель",
    sortKey: 220,
    time: "вторая половина XV в.",
    place: "Москва",
    participants: ["Иван III", "московские князья"],
    essence: "Политика Ивана III по присоединению независимых русских земель к Москве называлась собиранием русских земель.",
    results: "Эта политика лежала в основе формирования единого государства.",
    supportsPracticeItemIds: support("c4-ft-v3-q20"),
  },
  {
    id: "c4-f18",
    chapterId: 4,
    title: "Битва под Оршей",
    sortKey: 230,
    time: "1514 г.",
    place: "Орша",
    participants: ["московское войско", "литовское войско"],
    essence: "В 1514 году произошла битва под Оршей между московским князем и литовским войском.",
    results: "Это сражение связано с русско-литовской войной вокруг Смоленска.",
    supportsPracticeItemIds: support("c4-ft-v4-q16"),
  },
  {
    id: "c4-f19",
    chapterId: 4,
    title: "Ересь конца XV века",
    sortKey: 240,
    time: "конец XV в.",
    place: "Новгород и Москва",
    participants: ["сторонники ереси", "церковные власти"],
    essence: "Ересью называли религиозное течение, представители которого критиковали церковь и отказывались от почитания икон.",
    results: "Борьба с ересью стала важным церковным конфликтом конца XV века.",
    supportsPracticeItemIds: support("c4-ft-v4-q17"),
  },
  {
    id: "c4-f20",
    chapterId: 4,
    title: "Аристотель Фиораванти строит Успенский собор",
    sortKey: 250,
    time: "конец XV в.",
    place: "Москва, Кремль",
    participants: ["Аристотель Фиораванти", "Иван III"],
    essence: "Аристотель Фиораванти руководил строительством нового Успенского собора Московского Кремля.",
    results: "Итальянский зодчий стал одним из главных мастеров московского строительства при Иване III.",
    supportsPracticeItemIds: support("c4-ft-v4-q18", "c4-ft-v2-q24"),
  },
  {
    id: "c4-f21",
    chapterId: 4,
    title: "Софья Палеолог",
    sortKey: 251,
    time: "конец XV в.",
    place: "Москва",
    participants: ["Иван III", "Софья Палеолог"],
    essence: "Иван III женился на Софье Палеолог, племяннице последнего византийского императора.",
    results: "Брак подчёркивал преемственность Москвы от Византии.",
    supportsPracticeItemIds: support("c4-ft-v4-q20"),
  },
  {
    id: "c4-f22",
    chapterId: 4,
    title: "Шатровый стиль",
    sortKey: 260,
    time: "начало XVI в.",
    place: "Русское государство",
    participants: ["русские зодчие"],
    essence: "Шатровый стиль возник в начале XVI века и стал новым словом в русском каменном зодчестве.",
    results: "Этот стиль связан с переходом к новым формам храмового строительства.",
    supportsPracticeItemIds: support("c4-ft-v2-q20"),
  },
  {
    id: "c4-f23",
    chapterId: 4,
    title: "Софийский собор в Киеве",
    sortKey: 261,
    time: "XI в.",
    place: "Киев",
    participants: ["киевские мастера"],
    essence: "Софийский собор в Киеве был построен в XI веке.",
    results: "Собор стал одним из главных памятников древнерусского каменного зодчества.",
    supportsPracticeItemIds: support("c4-ft-v2-q24"),
  },
  {
    id: "c4-f24",
    chapterId: 4,
    title: "Успенский собор во Владимире",
    sortKey: 262,
    time: "XII в.",
    place: "Владимир",
    participants: ["Андрей Боголюбский", "владимирские мастера"],
    essence: "Успенский собор во Владимире был построен при Андрее Боголюбском в XII веке.",
    results: "Собор стал главным храмом Владимиро-Суздальской земли.",
    supportsPracticeItemIds: support("c4-ft-v2-q24"),
  },
  {
    id: "c4-f25",
    chapterId: 4,
    title: "Успенский собор Московского Кремля",
    sortKey: 263,
    time: "конец XV в.",
    place: "Москва, Кремль",
    participants: ["Иван III", "Аристотель Фиораванти"],
    essence: "Успенский собор Московского Кремля был построен при Иване III в конце XV века.",
    results: "Собор стал главным храмом Московского Кремля.",
    supportsPracticeItemIds: support("c4-ft-v2-q24"),
  },
  {
    id: "c4-f26",
    chapterId: 4,
    title: "Церковь Вознесения в Коломенском",
    sortKey: 264,
    time: "XVI в.",
    place: "Коломенское",
    participants: ["русские зодчие"],
    essence: "Церковь Вознесения в Коломенском относится к XVI веку и связана с шатровым стилем.",
    results: "Храм стал одним из известных памятников шатрового стиля.",
    supportsPracticeItemIds: support("c4-ft-v2-q24", "c4-ft-v2-q20"),
  },
];

export const chapter4SummaryEntries: ChapterSummaryEntry[] = chapter4StudyCards.map((card) => ({
  id: `${card.id}-summary`,
  chapterId: card.chapterId,
  sortKey: card.sortKey,
  dateLabel: card.time ?? "",
  title: card.title,
  body: card.essence,
}));
