import type { ChapterSummaryEntry, StudyCard } from "./course-data";

const support = (...ids: string[]) => ids;

export const chapter2StudyCards: StudyCard[] = [
  {
    id: "c2-f1",
    chapterId: 2,
    title: "Причины политической раздробленности Руси",
    sortKey: 100,
    time: "середина XII в.",
    place: "Русские земли",
    participants: ["князья", "бояре", "города"],
    essence: "Причиной политической раздробленности были рост вотчин, натуральное хозяйство, усобицы и отсутствие строгого порядка наследования.",
    results: "Эти причины ослабляли единство старого Киевского государства.",
    supportsPracticeItemIds: support("c2-ft-v4-q12"),
  },
  {
    id: "c2-f2",
    chapterId: 2,
    title: "Последствия политической раздробленности",
    sortKey: 101,
    time: "середина XII — начало XIII в.",
    place: "Русские земли",
    participants: ["князья", "города", "местные элиты"],
    essence: "Политическая раздробленность ускорила развитие местных городов и культурных центров.",
    results: "Одновременно она усилила усобицы и ослабила общую обороноспособность Руси.",
    supportsPracticeItemIds: support("c2-ft-v2-q12"),
  },
  {
    id: "c2-f3",
    chapterId: 2,
    title: "Первое упоминание Москвы",
    sortKey: 110,
    time: "1147 г.",
    place: "Москва",
    participants: ["Юрий Долгорукий", "Святослав Ольгович"],
    essence: "Москва впервые упоминается в летописи под 1147 годом как место встречи Юрия Долгорукого с союзниками.",
    results: "Позднее Москва стала центром объединения русских земель.",
    supportsPracticeItemIds: support("c2-ft-v3-q10"),
  },
  {
    id: "c2-f4",
    chapterId: 2,
    title: "Новгородское вече",
    sortKey: 120,
    time: "XII—XIII вв.",
    place: "Великий Новгород",
    participants: ["вече", "новгородцы"],
    essence: "В Новгороде высшей властью обладало вече — народное собрание горожан.",
    results: "Вече избирало должностных лиц и решало важные политические вопросы.",
    supportsPracticeItemIds: support("c2-ft-v2-q13"),
  },
  {
    id: "c2-f5",
    chapterId: 2,
    title: "Изгнание князя в Новгороде",
    sortKey: 121,
    time: "1136 г.",
    place: "Великий Новгород",
    participants: ["новгородцы", "князь"],
    essence: "В 1136 году новгородцы изгнали князя.",
    results: "Это событие считается началом Новгородской республики.",
    supportsPracticeItemIds: support("c2-ft-v3-q11"),
  },
  {
    id: "c2-f6",
    chapterId: 2,
    title: "Андрей Боголюбский переносит столицу во Владимир",
    sortKey: 130,
    time: "1157 г.",
    place: "Владимир-на-Клязьме",
    participants: ["Андрей Боголюбский"],
    essence: "Андрей Боголюбский первым перенёс столицу своего княжества во Владимир-на-Клязьме.",
    results: "При нём Владимир стал главным центром Северо-Восточной Руси и развивалось белокаменное строительство.",
    supportsPracticeItemIds: support("c2-ft-v2-q14", "c2-ft-v4-q11"),
  },
  {
    id: "c2-f7",
    chapterId: 2,
    title: "Всеволод Большое Гнездо",
    sortKey: 140,
    time: "конец XII — начало XIII в.",
    place: "Владимиро-Суздальская земля",
    participants: ["Всеволод Юрьевич"],
    essence: "Князь Всеволод Юрьевич вошёл в историю под прозвищем Большое Гнездо.",
    results: "Прозвище связано с его многочисленным потомством и политическим влиянием.",
    supportsPracticeItemIds: support("c2-ft-v3-q9", "c2-ft-v4-q22"),
  },
  {
    id: "c2-f8",
    chapterId: 2,
    title: "Юрий Долгорукий",
    sortKey: 150,
    time: "XII в.",
    place: "Северо-Восточная Русь",
    participants: ["Юрий Владимирович"],
    essence: "Юрий Владимирович вошёл в историю под прозвищем Долгорукий.",
    results: "С его именем связано первое летописное упоминание Москвы.",
    supportsPracticeItemIds: support("c2-ft-v4-q22"),
  },
  {
    id: "c2-f9",
    chapterId: 2,
    title: "Ярослав Осмомысл в Галиче",
    sortKey: 160,
    time: "вторая половина XII в.",
    place: "Галич",
    participants: ["Ярослав Владимирович"],
    essence: "В Галиче княжил Ярослав Владимирович, известный под прозвищем Осмомысл.",
    results: "Галич был одним из сильных центров Юго-Западной Руси.",
    supportsPracticeItemIds: support("c2-ft-v3-q23", "c2-ft-v4-q22"),
  },
  {
    id: "c2-f10",
    chapterId: 2,
    title: "Роман Мстиславич объединяет Галич и Волынь",
    sortKey: 170,
    time: "1199 г.",
    place: "Галич и Волынь",
    participants: ["Роман Мстиславич"],
    essence: "В 1199 году Роман Мстиславич объединил Галицкую и Волынскую земли.",
    results: "Так возник сильный политический центр Юго-Западной Руси.",
    supportsPracticeItemIds: support("c2-ft-v3-q23"),
  },
  {
    id: "c2-f11",
    chapterId: 2,
    title: "Правление Даниила Галицкого",
    sortKey: 180,
    time: "первая половина XIII в.",
    place: "Галицко-Волынская земля",
    participants: ["Даниил Галицкий"],
    essence: "Даниил Галицкий правил в первой половине XIII века и усиливал Галицко-Волынскую землю.",
    results: "При нём Галицко-Волынская земля сохраняла значение сильного княжества.",
    supportsPracticeItemIds: support("c2-ft-v3-q23"),
  },
  {
    id: "c2-f12",
    chapterId: 2,
    title: "Поход Батыя на Южную Русь",
    sortKey: 190,
    time: "1239—1241 гг.",
    place: "Южная Русь",
    participants: ["Батый", "жители Южной Руси"],
    essence: "В 1239—1241 годах южнорусские земли пережили поход Батыя.",
    results: "Нашествие стало тяжёлым испытанием для Южной Руси.",
    supportsPracticeItemIds: support("c2-ft-v3-q23"),
  },
  {
    id: "c2-f13",
    chapterId: 2,
    title: "Василий II Тёмный",
    sortKey: 200,
    time: "XV в.",
    place: "Москва",
    participants: ["Василий II"],
    essence: "Московский князь Василий II получил прозвище Тёмный после ослепления в междоусобной борьбе.",
    results: "Это прозвище используется в заданиях на сопоставление князей.",
    supportsPracticeItemIds: support("c2-ft-v4-q22"),
  },
];

export const chapter2SummaryEntries: ChapterSummaryEntry[] = chapter2StudyCards.map((card) => ({
  id: `${card.id}-summary`,
  chapterId: card.chapterId,
  sortKey: card.sortKey,
  dateLabel: card.time ?? "",
  title: card.title,
  body: card.essence,
}));
