import type { ChapterSummaryEntry, StudyCard } from "./course-data";

const support = (...ids: string[]) => ids;

export const chapter3StudyCards: StudyCard[] = [
  {
    id: "c3-f1",
    chapterId: 3,
    title: "Темучин принимает титул Чингисхана",
    sortKey: 90,
    time: "1206 г.",
    place: "Монголия",
    participants: ["Темучин", "монгольская знать"],
    essence: "В 1206 году Темучин принял титул Чингисхана, верховного правителя Монгольской империи.",
    results: "С этого началось оформление единой Монгольской империи.",
    supportsPracticeItemIds: support("c3-ft-v4-q15"),
  },
  {
    id: "c3-f2",
    chapterId: 3,
    title: "Битва на реке Калке",
    sortKey: 100,
    time: "1223 г.",
    place: "река Калка",
    participants: ["русские князья", "половцы", "Джебе", "Субедей"],
    essence: "В 1223 году на реке Калке произошло первое крупное столкновение русских князей с монголами.",
    results: "Русско-половецкие силы потерпели тяжёлое поражение.",
    supportsPracticeItemIds: support("c3-ft-v4-q24"),
  },
  {
    id: "c3-f3",
    chapterId: 3,
    title: "Батый возглавляет западный поход",
    sortKey: 110,
    time: "1237—1241 гг.",
    place: "Восточная Европа и Русь",
    participants: ["Батый", "монгольские войска"],
    essence: "Западный поход монголов, вторгшийся на Русь, возглавил Батый.",
    results: "Его поход стал началом разорения русских земель монголами.",
    supportsPracticeItemIds: support("c3-ft-v1-q8"),
  },
  {
    id: "c3-f4",
    chapterId: 3,
    title: "Гибель Рязани",
    sortKey: 111,
    time: "1237 г.",
    place: "Рязань",
    participants: ["Батый", "рязанцы"],
    essence: "В 1237 году монгольские войска Батыя разорили Рязань.",
    results: "Гибель Рязани была одним из первых ударов нашествия на Русь.",
    supportsPracticeItemIds: support("c3-ft-v4-q24"),
  },
  {
    id: "c3-f5",
    chapterId: 3,
    title: "Битва на реке Сити",
    sortKey: 112,
    time: "1238 г.",
    place: "река Сить",
    participants: ["монголы", "русские войска"],
    essence: "В 1238 году произошла битва на реке Сити.",
    results: "Поражение на Сити стало важным этапом разорения Северо-Восточной Руси.",
    supportsPracticeItemIds: support("c3-ft-v4-q24"),
  },
  {
    id: "c3-f6",
    chapterId: 3,
    title: "Козельск — злой город",
    sortKey: 113,
    time: "1238 г.",
    place: "Козельск",
    participants: ["жители Козельска", "монголы"],
    essence: "В 1238 году монголы прозвали Козельск «злым городом» за семинедельную оборону.",
    results: "Оборона Козельска стала символом упорного сопротивления.",
    supportsPracticeItemIds: support("c3-ft-v3-q8"),
  },
  {
    id: "c3-f7",
    chapterId: 3,
    title: "Взятие Киева монголами",
    sortKey: 114,
    time: "1240 г.",
    place: "Киев",
    participants: ["монголы", "киевляне"],
    essence: "В 1240 году монгольские войска взяли Киев.",
    results: "Падение Киева стало ключевым событием нашествия на Южную Русь.",
    supportsPracticeItemIds: support("c3-ft-v4-q24"),
  },
  {
    id: "c3-f8",
    chapterId: 3,
    title: "Невская битва",
    sortKey: 120,
    time: "1240 г.",
    place: "река Нева",
    participants: ["Александр Ярославич", "шведы", "новгородцы"],
    essence: "Невская битва произошла в 1240 году.",
    results: "После победы Александр Ярославич получил прозвище Невский.",
    supportsPracticeItemIds: support("c3-ft-v2-q10"),
  },
  {
    id: "c3-f9",
    chapterId: 3,
    title: "Ледовое побоище",
    sortKey: 130,
    time: "1242 г.",
    place: "Чудское озеро",
    participants: ["Александр Невский", "рыцари Ливонского ордена"],
    essence: "Ледовое побоище 1242 года было направлено против рыцарей Ливонского ордена.",
    results: "Победа остановила продвижение крестоносцев на восток.",
    supportsPracticeItemIds: support("c3-ft-v1-q18", "c3-ft-v4-q8"),
  },
  {
    id: "c3-f10",
    chapterId: 3,
    title: "Сарай-Бату — столица Золотой Орды",
    sortKey: 140,
    time: "середина XIII в.",
    place: "Нижнее Поволжье",
    participants: ["Батый", "ордынцы"],
    essence: "При хане Батые столицей Золотой Орды стал Сарай-Бату.",
    results: "Город стал центром ордынской власти в Нижнем Поволжье.",
    supportsPracticeItemIds: support("c3-ft-v2-q8"),
  },
  {
    id: "c3-f11",
    chapterId: 3,
    title: "Баскак контролирует сбор дани",
    sortKey: 150,
    time: "XIII—XIV вв.",
    place: "Русь и Орда",
    participants: ["баскак", "ордынские ханы"],
    essence: "Баскаком называли ордынского чиновника, который контролировал сбор дани на Руси.",
    results: "Баскаки были частью системы ордынского владычества.",
    supportsPracticeItemIds: support("c3-ft-v1-q21", "c3-ft-v2-q16"),
  },
  {
    id: "c3-f12",
    chapterId: 3,
    title: "Выход — дань Орде",
    sortKey: 151,
    time: "XIII—XIV вв.",
    place: "Русь и Орда",
    participants: ["русские князья", "ордынские ханы"],
    essence: "Выходом называли дань, которую русские земли платили Орде.",
    results: "Выплата выхода выражала зависимость Руси от Орды.",
    supportsPracticeItemIds: support("c3-ft-v1-q21"),
  },
  {
    id: "c3-f13",
    chapterId: 3,
    title: "Ярлык — ханская грамота",
    sortKey: 152,
    time: "XIII—XIV вв.",
    place: "Орда",
    participants: ["хан", "русские князья"],
    essence: "Ярлыком называли ханскую грамоту на княжение.",
    results: "Русские князья ездили в Орду за ярлыком, чтобы подтвердить власть.",
    supportsPracticeItemIds: support("c3-ft-v1-q21"),
  },
  {
    id: "c3-f14",
    chapterId: 3,
    title: "Численник проводит перепись",
    sortKey: 153,
    time: "XIII—XIV вв.",
    place: "Русь и Орда",
    participants: ["численник", "население Руси"],
    essence: "Численником называли ордынского чиновника, проводившего перепись населения.",
    results: "Перепись помогала Орде учитывать дань.",
    supportsPracticeItemIds: support("c3-ft-v1-q21"),
  },
  {
    id: "c3-f15",
    chapterId: 3,
    title: "Орда при хане Узбеке",
    sortKey: 160,
    time: "1313—1341 гг.",
    place: "Золотая Орда",
    participants: ["хан Узбек"],
    essence: "При хане Узбеке Золотая Орда достигла расцвета и приняла ислам как государственную религию.",
    results: "Правление Узбека стало одним из периодов наибольшей силы Орды.",
    supportsPracticeItemIds: support("c3-ft-v4-q14"),
  },
  {
    id: "c3-f16",
    chapterId: 3,
    title: "Великая замятня в Орде",
    sortKey: 161,
    time: "XIV в.",
    place: "Золотая Орда",
    participants: ["ордынские ханы"],
    essence: "В XIV веке длительную борьбу ханов за власть в Орде русские источники называли великой замятней.",
    results: "Замятня ослабляла Орду и меняла отношения с русскими княжествами.",
    supportsPracticeItemIds: support("c3-ft-v2-q19"),
  },
  {
    id: "c3-f17",
    chapterId: 3,
    title: "Иван Калита получает право собирать выход",
    sortKey: 170,
    time: "XIV в.",
    place: "Москва и Орда",
    participants: ["Иван Калита", "ордынский хан"],
    essence: "Иван Калита получил право собирать ордынский выход.",
    results: "Это право усилило Москву среди княжеств Северо-Восточной Руси.",
    supportsPracticeItemIds: support("c3-ft-v2-q22"),
  },
  {
    id: "c3-f18",
    chapterId: 3,
    title: "Иван Данилович — Калита",
    sortKey: 171,
    time: "XIV в.",
    place: "Москва",
    participants: ["Иван Данилович"],
    essence: "Иван Данилович вошёл в историю под прозвищем Калита.",
    results: "Прозвище используется для различения московских князей.",
    supportsPracticeItemIds: support("c3-ft-v1-q22"),
  },
  {
    id: "c3-f19",
    chapterId: 3,
    title: "Ярослав Владимирович — Мудрый",
    sortKey: 172,
    time: "XI в.",
    place: "Киевская Русь",
    participants: ["Ярослав Владимирович"],
    essence: "Ярослав Владимирович известен под прозвищем Мудрый.",
    results: "Это прозвище связано с образом князя-законодателя и покровителя культуры.",
    supportsPracticeItemIds: support("c3-ft-v1-q22"),
  },
  {
    id: "c3-f20",
    chapterId: 3,
    title: "Дмитрий Иванович — Донской",
    sortKey: 173,
    time: "XIV в.",
    place: "Москва",
    participants: ["Дмитрий Иванович"],
    essence: "Дмитрий Иванович получил прозвище Донской после победы на Дону.",
    results: "Прозвище связано с Куликовской битвой.",
    supportsPracticeItemIds: support("c3-ft-v1-q22"),
  },
  {
    id: "c3-f21",
    chapterId: 3,
    title: "Александр Ярославич — Невский",
    sortKey: 174,
    time: "XIII в.",
    place: "Новгородская земля",
    participants: ["Александр Ярославич"],
    essence: "Александр Ярославич получил прозвище Невский после победы на Неве.",
    results: "Прозвище напоминает о Невской битве 1240 года.",
    supportsPracticeItemIds: support("c3-ft-v1-q22"),
  },
  {
    id: "c3-f22",
    chapterId: 3,
    title: "Победа на реке Воже",
    sortKey: 180,
    time: "1378 г.",
    place: "река Вожа",
    participants: ["Дмитрий Донской", "ордынцы"],
    essence: "Победа на реке Воже в 1378 году стала первой крупной победой русских войск над ордынцами.",
    results: "Она укрепила уверенность Москвы перед борьбой с Мамаем.",
    supportsPracticeItemIds: support("c3-ft-v3-q13"),
  },
  {
    id: "c3-f23",
    chapterId: 3,
    title: "Куликовская битва",
    sortKey: 190,
    time: "8 сентября 1380 г.",
    place: "Куликово поле",
    participants: ["Дмитрий Донской", "Мамай", "русские полки"],
    essence: "8 сентября 1380 года произошла Куликовская битва.",
    results: "В ней русские войска под руководством Дмитрия Донского победили Мамая.",
    supportsPracticeItemIds: support("c3-ft-v2-q15", "c3-ft-v2-q22"),
  },
  {
    id: "c3-f24",
    chapterId: 3,
    title: "Сергий Радонежский благословляет Дмитрия Донского",
    sortKey: 191,
    time: "1380 г.",
    place: "Троицкий монастырь",
    participants: ["Сергий Радонежский", "Дмитрий Донской"],
    essence: "Сергий Радонежский благословил Дмитрия Донского перед Куликовской битвой.",
    results: "Этот факт связывает Сергия с духовной поддержкой борьбы с Ордой.",
    supportsPracticeItemIds: support("c3-ft-v2-q21"),
  },
  {
    id: "c3-f25",
    chapterId: 3,
    title: "Нестор — летописец",
    sortKey: 192,
    time: "начало XII в.",
    place: "Киев",
    participants: ["Нестор"],
    essence: "Нестор связан с созданием «Повести временных лет».",
    results: "Он выступает как книжник и летописец в заданиях на роли исторических лиц.",
    supportsPracticeItemIds: support("c3-ft-v2-q21"),
  },
  {
    id: "c3-f26",
    chapterId: 3,
    title: "Аристотель Фиораванти — зодчий",
    sortKey: 193,
    time: "конец XV в.",
    place: "Москва",
    participants: ["Аристотель Фиораванти"],
    essence: "Аристотель Фиораванти был итальянским зодчим, руководившим строительством Успенского собора Московского Кремля.",
    results: "Его роль относится к культуре Московского государства.",
    supportsPracticeItemIds: support("c3-ft-v2-q21"),
  },
  {
    id: "c3-f27",
    chapterId: 3,
    title: "Евпатий Коловрат — герой сопротивления",
    sortKey: 194,
    time: "1237 г.",
    place: "Рязань",
    participants: ["Евпатий Коловрат"],
    essence: "Евпатий Коловрат вошёл в память как герой сопротивления после разорения Рязани Батыем.",
    results: "В заданиях он соотносится с героическим сопротивлением нашествию.",
    supportsPracticeItemIds: support("c3-ft-v2-q21"),
  },
  {
    id: "c3-f28",
    chapterId: 3,
    title: "Святослав разгромил Хазарский каганат",
    sortKey: 195,
    time: "X в.",
    place: "Хазария",
    participants: ["Святослав Игоревич", "хазары"],
    essence: "Святослав Игоревич разгромил Хазарский каганат.",
    results: "Этот факт связывает князя Святослава с восточными походами.",
    supportsPracticeItemIds: support("c3-ft-v2-q22"),
  },
  {
    id: "c3-f29",
    chapterId: 3,
    title: "Ярослав Мудрый и Русская Правда",
    sortKey: 196,
    time: "XI в.",
    place: "Киевская Русь",
    participants: ["Ярослав Мудрый"],
    essence: "С правлением Ярослава Мудрого связано создание Русской Правды.",
    results: "Русская Правда была главным сводом письменных законов Древней Руси.",
    supportsPracticeItemIds: support("c3-ft-v2-q22"),
  },
  {
    id: "c3-f30",
    chapterId: 3,
    title: "Александр Невский против Ливонского ордена",
    sortKey: 200,
    time: "1242 г.",
    place: "Чудское озеро",
    participants: ["Александр Невский", "рыцари Ливонского ордена"],
    essence: "Александр Невский сражался с рыцарями Ливонского ордена в Ледовом побоище.",
    results: "Эта пара нужна для сопоставления князя и противника.",
    supportsPracticeItemIds: support("c3-ft-v3-q22"),
  },
  {
    id: "c3-f31",
    chapterId: 3,
    title: "Дмитрий Донской против Мамая",
    sortKey: 201,
    time: "1380 г.",
    place: "Куликово поле",
    participants: ["Дмитрий Донской", "Мамай"],
    essence: "Дмитрий Донской сражался с Мамаем в Куликовской битве.",
    results: "Эта пара показывает главных противников битвы 1380 года.",
    supportsPracticeItemIds: support("c3-ft-v3-q22"),
  },
  {
    id: "c3-f32",
    chapterId: 3,
    title: "Джебе и Субедей — полководцы Чингисхана",
    sortKey: 202,
    time: "начало XIII в.",
    place: "Монгольская империя",
    participants: ["Чингисхан", "Джебе", "Субедей"],
    essence: "Джебе и Субедей были полководцами Чингисхана.",
    results: "Их поход привёл к первому столкновению с русскими князьями на Калке.",
    supportsPracticeItemIds: support("c3-ft-v3-q22"),
  },
  {
    id: "c3-f33",
    chapterId: 3,
    title: "Стояние на Угре",
    sortKey: 210,
    time: "1480 г.",
    place: "река Угра",
    participants: ["Иван III", "хан Ахмат"],
    essence: "В 1480 году произошло Стояние на реке Угре между Иваном III и ханом Ахматом.",
    results: "Это событие окончательно освободило Русь от ордынского владычества.",
    supportsPracticeItemIds: support("c3-ft-v3-q14", "c3-ft-v3-q22"),
  },
];

export const chapter3SummaryEntries: ChapterSummaryEntry[] = chapter3StudyCards.map((card) => ({
  id: `${card.id}-summary`,
  chapterId: card.chapterId,
  sortKey: card.sortKey,
  dateLabel: card.time ?? "",
  title: card.title,
  body: card.essence,
}));
