import type { BookSection, BookTarget } from "./book-data";

export const chapter1BookSections: BookSection[] = [
  {
    id: "c1-b1",
    chapterId: 1,
    title: "§ 1. Великое переселение народов и древние жители нашей страны",
    sortKey: 100,
    sourcePath: "books/russian-history/part-1/2.php.html",
  },
  {
    id: "c1-b2",
    chapterId: 1,
    title: "§ 2-3. Восточные славяне и их соседи",
    sortKey: 110,
    sourcePath: "books/russian-history/part-1/3.php.html",
  },
  {
    id: "c1-b3",
    chapterId: 1,
    title: "§ 4. Начало династии Рюриковичей",
    sortKey: 120,
    sourcePath: "books/russian-history/part-1/4.php.html",
  },
  {
    id: "c1-b4",
    chapterId: 1,
    title: "§ 5-6. Русь при Игоре, Ольге, Святославе",
    sortKey: 130,
    sourcePath: "books/russian-history/part-1/5.php.html",
  },
  {
    id: "c1-b5",
    chapterId: 1,
    title: "§ 7-8. Русь при Владимире Святом",
    sortKey: 140,
    sourcePath: "books/russian-history/part-1/6.php.html",
  },
  {
    id: "c1-b6",
    chapterId: 1,
    title: "§ 9. Расцвет Руси при Ярославе Мудром",
    sortKey: 150,
    sourcePath: "books/russian-history/part-1/7.php.html",
  },
  {
    id: "c1-b7",
    chapterId: 1,
    title: "§ 10-11. Наследники Ярослава Мудрого",
    sortKey: 160,
    sourcePath: "books/russian-history/part-1/8.php.html",
  },
  {
    id: "c1-b8",
    chapterId: 1,
    title: "§ 12. Русь при Владимире Мономахе",
    sortKey: 170,
    sourcePath: "books/russian-history/part-1/9.php.html",
  },
];

const summaryTargetsFor = (targets: Record<string, BookTarget>): Record<string, BookTarget> =>
  Object.fromEntries(
    Object.entries(targets).map(([cardId, target]) => [`${cardId}-summary`, target])
  );

export const chapter1StudyCardTargets: Record<string, BookTarget> = {
  "c1-f1": { sectionId: "c1-b1" },
  "c1-f2": { sectionId: "c1-b1" },
  "c1-f3": { sectionId: "c1-b1" },
  "c1-f4": { sectionId: "c1-b1" },
  "c1-f5": { sectionId: "c1-b1" },
  "c1-f6": { sectionId: "c1-b1" },
  "c1-f7": { sectionId: "c1-b1" },
  "c1-f8": { sectionId: "c1-b2" },
  "c1-f9": { sectionId: "c1-b2" },
  "c1-f10": { sectionId: "c1-b2" },
  "c1-f11": { sectionId: "c1-b2" },
  "c1-f12": { sectionId: "c1-b2" },
  "c1-f13": { sectionId: "c1-b2" },
  "c1-f14": { sectionId: "c1-b2" },
  "c1-f15": { sectionId: "c1-b2" },
  "c1-f16": { sectionId: "c1-b2" },
  "c1-f17": { sectionId: "c1-b2" },
  "c1-f18": { sectionId: "c1-b2" },
  "c1-f19": { sectionId: "c1-b2" },
  "c1-f20": { sectionId: "c1-b2" },
  "c1-f21": { sectionId: "c1-b2" },
  "c1-f22": { sectionId: "c1-b2" },
  "c1-f23": { sectionId: "c1-b2" },
  "c1-f24": { sectionId: "c1-b3" },
  "c1-f25": { sectionId: "c1-b3" },
  "c1-f26": { sectionId: "c1-b3" },
  "c1-f27": { sectionId: "c1-b3" },
  "c1-f28": { sectionId: "c1-b4" },
  "c1-f29": { sectionId: "c1-b4" },
  "c1-f30": { sectionId: "c1-b4" },
  "c1-f31": { sectionId: "c1-b4" },
  "c1-f32": { sectionId: "c1-b4" },
  "c1-f33": { sectionId: "c1-b4" },
  "c1-f34": { sectionId: "c1-b5" },
  "c1-f35": { sectionId: "c1-b5" },
  "c1-f36": { sectionId: "c1-b5" },
  "c1-f37": { sectionId: "c1-b5" },
  "c1-f38": { sectionId: "c1-b5" },
  "c1-f39": { sectionId: "c1-b6" },
  "c1-f40": { sectionId: "c1-b6" },
  "c1-f41": { sectionId: "c1-b6" },
  "c1-f42": { sectionId: "c1-b6" },
  "c1-f43": { sectionId: "c1-b6" },
  "c1-f44": { sectionId: "c1-b7" },
  "c1-f45": { sectionId: "c1-b7" },
  "c1-f46": { sectionId: "c1-b8" },
  "c1-f47": { sectionId: "c1-b8" },
  "c1-f48": { sectionId: "c1-b6" },
  "c1-f49": { sectionId: "c1-b7" },
  "c1-f50": { sectionId: "c1-b7" },
  "c1-f51": { sectionId: "c1-b7" },
  "c1-f52": { sectionId: "c1-b7" },
  "c1-f53": { sectionId: "c3-b3" },
};

export const chapter1SummaryTargets: Record<string, BookTarget> = summaryTargetsFor(
  chapter1StudyCardTargets
);
