import type { BookSection, BookTarget } from "./book-data";

export const chapter3BookSections: BookSection[] = [
  {
    id: "c3-b1",
    chapterId: 3,
    title: "§15. Европейская индустриализация и предпосылки реформ в России",
    sortKey: 300,
    sourcePath: "books/russian-history/part-1/17.php.html",
  },
  {
    id: "c3-b2",
    chapterId: 3,
    title: "§16. Александр II: Начало правления. Крестьянская реформа 1861 г.",
    sortKey: 310,
    sourcePath: "books/russian-history/part-1/18.php.html",
  },
  {
    id: "c3-b3",
    chapterId: 3,
    title: "§17. Реформы 1860—1870-х гг.: Социальная и правовая модернизация",
    sortKey: 320,
    sourcePath: "books/russian-history/part-1/19.php.html",
  },
  {
    id: "c3-b4",
    chapterId: 3,
    title: "§18. Социально-экономическое развитие страны в пореформенный период",
    sortKey: 330,
    sourcePath: "books/russian-history/part-1/20.php.html",
  },
  {
    id: "c3-b5",
    chapterId: 3,
    title: "§19-20. Общественное движение при Александре II и политика правительства",
    sortKey: 340,
    sourcePath: "books/russian-history/part-1/21.php.html",
  },
  {
    id: "c3-b6",
    chapterId: 3,
    title: "Национальная и религиозная политика Александра II. Национальный вопрос в Европе и в России",
    sortKey: 350,
    sourcePath: "books/russian-history/part-1/22.php.html",
  },
  {
    id: "c3-b7",
    chapterId: 3,
    title: "§21. Внешняя политика Александра II. Русско-турецкая война 1877—1878 гг.",
    sortKey: 360,
    sourcePath: "books/russian-history/part-1/23.php.html",
  },
];

export const chapter3StudyCardTargets: Record<string, BookTarget> = {
  "c3-s1": { sectionId: "c3-b1", anchorId: "c3-industrialization-europe" },
  "c3-s2": { sectionId: "c3-b1", anchorId: "c3-industrialization-russia" },
  "c3-s3": { sectionId: "c3-b1", anchorId: "c3-reform-preconditions" },
  "c3-s4": { sectionId: "c3-b2", anchorId: "c3-peasant-reform-preparation" },
  "c3-s5": { sectionId: "c3-b2", anchorId: "c3-peasant-reform-terms" },
  "c3-s6": { sectionId: "c3-b2", anchorId: "c3-peasant-reform-results" },
  "c3-s7": { sectionId: "c3-b3", anchorId: "c3-zemstvo-reform" },
  "c3-s8": { sectionId: "c3-b3", anchorId: "c3-city-reform" },
  "c3-s9": { sectionId: "c3-b3", anchorId: "c3-judicial-reform" },
  "c3-s10": { sectionId: "c3-b3", anchorId: "c3-military-reform" },
  "c3-s11": { sectionId: "c3-b3", anchorId: "c3-education-reform" },
  "c3-s12": { sectionId: "c3-b4", anchorId: "c3-finance-railways" },
  "c3-s13": { sectionId: "c3-b4", anchorId: "c3-industry-growth" },
  "c3-s14": { sectionId: "c3-b5", anchorId: "c3-conservative-liberal" },
  "c3-s15": { sectionId: "c3-b5", anchorId: "c3-populism" },
  "c3-s16": { sectionId: "c3-b5", anchorId: "c3-populism-terror" },
  "c3-s17": { sectionId: "c3-b5", anchorId: "c3-loris-melikov" },
  "c3-s18": { sectionId: "c3-b6", anchorId: "c3-polish-uprising" },
  "c3-s19": { sectionId: "c3-b7", anchorId: "c3-gorchakov-london" },
  "c3-s20": { sectionId: "c3-b7", anchorId: "c3-central-asia" },
  "c3-s21": { sectionId: "c3-b7", anchorId: "c3-far-east" },
  "c3-s22": { sectionId: "c3-b7", anchorId: "c3-russo-turkish-war" },
};

export const chapter3SummaryTargets: Record<string, BookTarget> = {
  "c3-t1": { sectionId: "c3-b1", anchorId: "c3-industrialization-russia" },
  "c3-t2": { sectionId: "c3-b2", anchorId: "c3-alexander-ii-start" },
  "c3-t3": { sectionId: "c3-b2", anchorId: "c3-peasant-reform-preparation" },
  "c3-t4": { sectionId: "c3-b7", anchorId: "c3-far-east" },
  "c3-t5": { sectionId: "c3-b2", anchorId: "c3-peasant-reform-terms" },
  "c3-t6": { sectionId: "c3-b6", anchorId: "c3-polish-uprising" },
  "c3-t7": { sectionId: "c3-b3", anchorId: "c3-zemstvo-reform" },
  "c3-t8": { sectionId: "c3-b7", anchorId: "c3-central-asia" },
  "c3-t9": { sectionId: "c3-b7", anchorId: "c3-alaska" },
  "c3-t10": { sectionId: "c3-b3", anchorId: "c3-city-reform" },
  "c3-t11": { sectionId: "c3-b7", anchorId: "c3-gorchakov-london" },
  "c3-t12": { sectionId: "c3-b3", anchorId: "c3-military-reform" },
  "c3-t13": { sectionId: "c3-b5", anchorId: "c3-populism" },
  "c3-t14": { sectionId: "c3-b7", anchorId: "c3-russo-turkish-war" },
  "c3-t15": { sectionId: "c3-b7", anchorId: "c3-russo-turkish-war" },
  "c3-t16": { sectionId: "c3-b5", anchorId: "c3-populism-terror" },
  "c3-t17": { sectionId: "c3-b5", anchorId: "c3-loris-melikov" },
  "c3-t18": { sectionId: "c3-b5", anchorId: "c3-loris-melikov" },
};
