import type { BookSection, BookTarget } from "./book-data";

export const chapter5BookSections: BookSection[] = [
  {
    id: "c5-b1",
    chapterId: 5,
    title: "§26. Россия и мир на рубеже XIX—XX вв.: Динамика и противоречия развития",
    sortKey: 500,
    sourcePath: "books/russian-history/part-2/10.php.html",
  },
  {
    id: "c5-b2",
    chapterId: 5,
    title: "§27. Социально-экономическое развитие страны на рубеже XIX—XX вв.",
    sortKey: 510,
    sourcePath: "books/russian-history/part-2/11.php.html",
  },
  {
    id: "c5-b3",
    chapterId: 5,
    title: "§28. Николай II: начало правления. Политическое развитие страны в 1894—1904 гг.",
    sortKey: 520,
    sourcePath: "books/russian-history/part-2/12.php.html",
  },
  {
    id: "c5-b4",
    chapterId: 5,
    title: "§29. Внешняя политика Николая II. Русско-японская война 1904—1905 гг.",
    sortKey: 530,
    sourcePath: "books/russian-history/part-2/13.php.html",
  },
  {
    id: "c5-b5",
    chapterId: 5,
    title: "§30. Первая российская революция и политические реформы 1905—1907 гг.",
    sortKey: 540,
    sourcePath: "books/russian-history/part-2/14.php.html",
  },
  {
    id: "c5-b6",
    chapterId: 5,
    title: "§31. Социально-экономические реформы П. А. Столыпина",
    sortKey: 550,
    sourcePath: "books/russian-history/part-2/15.php.html",
  },
  {
    id: "c5-b7",
    chapterId: 5,
    title: "§32. Политическое развитие страны в 1907—1914 гг.",
    sortKey: 560,
    sourcePath: "books/russian-history/part-2/16.php.html",
  },
  {
    id: "c5-b8",
    chapterId: 5,
    title: "§33. Серебряный век русской культуры",
    sortKey: 570,
    sourcePath: "books/russian-history/part-2/17.php.html",
  },
];

export const chapter5StudyCardTargets: Record<string, BookTarget> = {
  "c5-s1": { sectionId: "c5-b1", anchorId: "c5-world-start" },
  "c5-s2": { sectionId: "c5-b1", anchorId: "c5-empire-population" },
  "c5-s3": { sectionId: "c5-b1", anchorId: "c5-modernization" },
  "c5-s4": { sectionId: "c5-b2", anchorId: "c5-economy-growth" },
  "c5-s5": { sectionId: "c5-b3", anchorId: "c5-nicholas-start" },
  "c5-s6": { sectionId: "c5-b4", anchorId: "c5-hague" },
  "c5-s7": { sectionId: "c5-b5", anchorId: "c5-revolution-causes" },
  "c5-s8": { sectionId: "c5-b5", anchorId: "c5-october-manifesto" },
  "c5-s9": { sectionId: "c5-b6", anchorId: "c5-stolypin-course" },
  "c5-s10": { sectionId: "c5-b6", anchorId: "c5-agrarian-reform" },
  "c5-s11": { sectionId: "c5-b7", anchorId: "c5-third-duma" },
  "c5-s12": { sectionId: "c5-b7", anchorId: "c5-national-policy" },
  "c5-s13": { sectionId: "c5-b8", anchorId: "c5-silver-age-science" },
  "c5-s14": { sectionId: "c5-b8", anchorId: "c5-silver-age-literature" },
  "c5-s15": { sectionId: "c5-b8", anchorId: "c5-silver-age-architecture" },
};

export const chapter5SummaryTargets: Record<string, BookTarget> = {
  "c5-t1": { sectionId: "c5-b3", anchorId: "c5-nicholas-start" },
  "c5-t2": { sectionId: "c5-b3", anchorId: "c5-nicholas-start" },
  "c5-t3": { sectionId: "c5-b2", anchorId: "c5-economy-growth" },
  "c5-t4": { sectionId: "c5-b3", anchorId: "c5-rsdrp" },
  "c5-t5": { sectionId: "c5-b4", anchorId: "c5-far-east" },
  "c5-t6": { sectionId: "c5-b3", anchorId: "c5-zubatov" },
  "c5-t7": { sectionId: "c5-b3", anchorId: "c5-rsdrp" },
  "c5-t8": { sectionId: "c5-b4", anchorId: "c5-war-start" },
  "c5-t9": { sectionId: "c5-b5", anchorId: "c5-bloody-sunday" },
  "c5-t10": { sectionId: "c5-b4", anchorId: "c5-portsmouth-entente" },
  "c5-t11": { sectionId: "c5-b5", anchorId: "c5-october-manifesto" },
  "c5-t12": { sectionId: "c5-b5", anchorId: "c5-fundamental-laws" },
  "c5-t13": { sectionId: "c5-b6", anchorId: "c5-stolypin-course" },
  "c5-t14": { sectionId: "c5-b7", anchorId: "c5-third-duma" },
  "c5-t15": { sectionId: "c5-b4", anchorId: "c5-portsmouth-entente" },
  "c5-t16": { sectionId: "c5-b7", anchorId: "c5-society-vs-power" },
  "c5-t17": { sectionId: "c5-b7", anchorId: "c5-revolutionary-mood" },
  "c5-t18": { sectionId: "c5-b8", anchorId: "c5-silver-age-literature" },
};
