import type { BookSection, BookTarget } from "./book-data";

export const chapter4BookSections: BookSection[] = [
  {
    id: "c4-b1",
    chapterId: 4,
    title: "§22. Александр III: особенности внутренней политики",
    sortKey: 400,
    sourcePath: "books/russian-history/part-2/1.php.html",
  },
  {
    id: "c4-b2",
    chapterId: 4,
    title: "§23. Перемены в экономике и социальном строе",
    sortKey: 410,
    sourcePath: "books/russian-history/part-2/2.php.html",
  },
  {
    id: "c4-b3",
    chapterId: 4,
    title: "§24. Общественное движение в 1880-х — первой половине 1890-х гг.",
    sortKey: 420,
    sourcePath: "books/russian-history/part-2/3.php.html",
  },
  {
    id: "c4-b4",
    chapterId: 4,
    title: "Национальная и религиозная политика Александра III",
    sortKey: 430,
    sourcePath: "books/russian-history/part-2/4.php.html",
  },
  {
    id: "c4-b5",
    chapterId: 4,
    title: "§25. Внешняя политика Александра III",
    sortKey: 440,
    sourcePath: "books/russian-history/part-2/5.php.html",
  },
  {
    id: "c4-b6",
    chapterId: 4,
    title:
      "Культурное пространство империи во второй половине XIX в.: Достижения российской науки и образования",
    sortKey: 450,
    sourcePath: "books/russian-history/part-2/6.php.html",
  },
  {
    id: "c4-b7",
    chapterId: 4,
    title: "Культурное пространство империи во второй половине XIX в.: Русская литература",
    sortKey: 460,
    sourcePath: "books/russian-history/part-2/7.php.html",
  },
  {
    id: "c4-b8",
    chapterId: 4,
    title:
      "Культурное пространство империи во второй половине XIX в.: Художественная культура народов России",
    sortKey: 470,
    sourcePath: "books/russian-history/part-2/8.php.html",
  },
  {
    id: "c4-b9",
    chapterId: 4,
    title: "Повседневная жизнь разных слоёв населения в XIX в.",
    sortKey: 480,
    sourcePath: "books/russian-history/part-2/9.php.html",
  },
];

export const chapter4StudyCardTargets: Record<string, BookTarget> = {
  "c4-s1": { sectionId: "c4-b1", anchorId: "c4-alexander-iii-start" },
  "c4-s2": { sectionId: "c4-b1", anchorId: "c4-counterreforms" },
  "c4-s3": { sectionId: "c4-b1", anchorId: "c4-state-order" },
  "c4-s4": { sectionId: "c4-b1", anchorId: "c4-education-censorship" },
  "c4-s5": { sectionId: "c4-b1", anchorId: "c4-populist-policy" },
  "c4-s6": { sectionId: "c4-b1", anchorId: "c4-populist-policy" },
  "c4-s7": { sectionId: "c4-b2", anchorId: "c4-bunge-policy" },
  "c4-s8": { sectionId: "c4-b2", anchorId: "c4-vyshnegradsky-witte" },
  "c4-s9": { sectionId: "c4-b2", anchorId: "c4-agriculture" },
  "c4-s10": { sectionId: "c4-b2", anchorId: "c4-peasantry" },
  "c4-s11": { sectionId: "c4-b2", anchorId: "c4-nobility" },
  "c4-s12": { sectionId: "c4-b2", anchorId: "c4-proletariat" },
  "c4-s13": { sectionId: "c4-b3", anchorId: "c4-revolutionary-populism" },
  "c4-s14": { sectionId: "c4-b3", anchorId: "c4-russian-marxism" },
  "c4-s15": { sectionId: "c4-b3", anchorId: "c4-liberal-movement" },
  "c4-s16": { sectionId: "c4-b4", anchorId: "c4-religious-policy" },
  "c4-s17": { sectionId: "c4-b4", anchorId: "c4-western-borderlands" },
  "c4-s18": { sectionId: "c4-b5", anchorId: "c4-germany-tensions" },
  "c4-s19": { sectionId: "c4-b5", anchorId: "c4-franco-russian-alliance" },
  "c4-s20": { sectionId: "c4-b5", anchorId: "c4-central-asia-annexation" },
  "c4-s21": { sectionId: "c4-b6", anchorId: "c4-print-libraries-museums" },
  "c4-s22": { sectionId: "c4-b6", anchorId: "c4-science" },
  "c4-s23": { sectionId: "c4-b7", anchorId: "c4-literature-golden-age" },
  "c4-s24": { sectionId: "c4-b8", anchorId: "c4-painting" },
  "c4-s25": { sectionId: "c4-b8", anchorId: "c4-sculpture-architecture" },
  "c4-s26": { sectionId: "c4-b8", anchorId: "c4-sculpture-architecture" },
  "c4-s27": { sectionId: "c4-b8", anchorId: "c4-music" },
  "c4-s28": { sectionId: "c4-b9", anchorId: "c4-urbanization" },
  "c4-s29": { sectionId: "c4-b9", anchorId: "c4-village-life" },
  "c4-s30": { sectionId: "c4-b6", anchorId: "c4-education-second-half" },
  "c4-s31": { sectionId: "c4-b9", anchorId: "c4-urbanization" },
};

export const chapter4SummaryTargets: Record<string, BookTarget> = {
  "c4-t1": { sectionId: "c4-b1", anchorId: "c4-alexander-iii-start" },
  "c4-t2": { sectionId: "c4-b1", anchorId: "c4-counterreforms" },
  "c4-t3": { sectionId: "c4-b1", anchorId: "c4-state-order" },
  "c4-t4": { sectionId: "c4-b1", anchorId: "c4-populist-policy" },
  "c4-t5": { sectionId: "c4-b3", anchorId: "c4-russian-marxism" },
  "c4-t6": { sectionId: "c4-b1", anchorId: "c4-education-censorship" },
  "c4-t7": { sectionId: "c4-b1", anchorId: "c4-state-order" },
  "c4-t8": { sectionId: "c4-b3", anchorId: "c4-revolutionary-populism" },
  "c4-t9": { sectionId: "c4-b2", anchorId: "c4-vyshnegradsky-witte" },
  "c4-t10": { sectionId: "c4-b5", anchorId: "c4-germany-tensions" },
  "c4-t11": { sectionId: "c4-b5", anchorId: "c4-franco-russian-alliance" },
  "c4-t12": { sectionId: "c4-b2", anchorId: "c4-agriculture" },
  "c4-t13": { sectionId: "c4-b5", anchorId: "c4-franco-russian-alliance" },
  "c4-t14": { sectionId: "c4-b6", anchorId: "c4-education-second-half" },
  "c4-t15": { sectionId: "c4-b6", anchorId: "c4-science" },
  "c4-t16": { sectionId: "c4-b8", anchorId: "c4-painting" },
};
